---
title: "step_two_indexing"
author: "Zhuoran"
date: "17/11/2021"
output: html_document
---


#libraries
```{r}
library(foreign)
library(dplyr)
library(lubridate)
library(gbm)
library(pdp)
library(doParallel)
library(foreach)
library(ggplot2)
```


#import data
```{r}
full_data = read.csv("./data/raw_data_2004_2020_RPPI.csv")[-1]

full_data$LA_DESC = as.factor(full_data$LA_DESC)
full_data$PROP_CLA = as.factor(full_data$PROP_CLA)
full_data$submarket = as.factor(full_data$submarket)
full_data$logprice = log(full_data$SALE1)

#we can use some properties which sale more than twice as the index test part(use parcel id to track them, shared land properties may have the same land id)
#temp = data.frame(table(full_data$PARCEL_I))
#sum(temp$Freq>2)
```


#prepare data for modeling
```{r}
model = data.frame(logprice = full_data$logprice,
                   quarter_num = full_data$quarter_num, 
                   LAND_ARE = full_data$LAND_ARE, 
                   AREA_HSE = full_data$AREA_HSE, 
                   age = full_data$age, 
                   BEDS = full_data$BEDS,
                   BATHS = full_data$BATHS, 
                   DINING = full_data$DINING, 
                   KITCHEN = full_data$KITCHEN, 
                   FAMILY = full_data$FAMILY, 
                   STUDY = full_data$STUDY, 
                   GAMES = full_data$GAMES, 
                   LOUNGE = full_data$LOUNGE, 
                   MEALS = full_data$MEALS, 
                   carpark = full_data$carpark, 
                   LA_DESC = full_data$LA_DESC, 
                   PROP_CLA = full_data$PROP_CLA, 
                   centlong = full_data$centlong, 
                   centlat = full_data$centlat, 
                   TENCRT = full_data$TENCRT,
                   d_pool = full_data$d_pool, 
                   d_brick = full_data$d_brick, 
                   d_tile = full_data$d_tile,
                   submarket = full_data$submarket)
```


#indexing full data process
```{r}
set.seed(717)
gbm_full = gbm(logprice ~ quarter_num + LAND_ARE + AREA_HSE + age + BEDS + BATHS + DINING + KITCHEN + FAMILY + STUDY + GAMES + LOUNGE + MEALS + carpark + LA_DESC + PROP_CLA + centlong + centlat + d_pool + d_brick + d_tile + TENCRT + submarket, data = model, distribution = "gaussian", n.trees = 2000, interaction.depth = 14, shrinkage = 0.05, n.minobsinnode = 15, bag.fraction = 0.5) #distribution = "laplace", if use laplace or MAE, two or more dimensional pdp generates the same predict numbers. Thus, gaussian (MSE) could be better. And then, paper one, the difference is negligible.


#partial dependence plot: just quarter number
set.seed(717)
pdp_quarters = partial(object = gbm_full,
                       train = model,
                       pred.var = "quarter_num",
                       n.trees = 2000,
                       pred.grid = data.frame(quarter_num = 1:max(model$quarter_num)))


#partial dependence plot: quarter number and submarket
set.seed(717)
pdp_quarters_submarket = partial(object = gbm_full,
                       train = model,
                       pred.var = c("quarter_num", "submarket"),
                       n.trees = 2000,
                       pred.grid = data.frame(quarter_num = sort(rep(1:max(model$quarter_num), 5)), submarket = c("inner","northeast","northwest","southeast","southwest")))


#partial dependence plot: quarter number and property class
set.seed(717)
pdp_quarters_class = partial(object = gbm_full,
                       train = model,
                       pred.var = c("quarter_num", "PROP_CLA"),
                       n.trees = 2000,
                       pred.grid = data.frame(quarter_num = sort(rep(1:max(model$quarter_num), 20)), PROP_CLA = c("APARTMENT HO", "DETACHED HOU", "DUPLEX      ", "FLAT        ", "GROUP HOUSE ", "HOLIDAY UNIT", "HOME UNIT   ", "HOUSE       ", "HOUSE - FLAT", "HOUSE - GRAN", "HOUSE - LAND", "HOUSE - UNIT", "PATIO HOUSE ", "QUADRUPLEX  ", "ROW HOUSE   ", "SEMI-DETACHE", "TERRACE HOUS", "TOWN HOUSE  ", "TRIPLEX     ", "VILLA HOUSE ")))


#partial dependence plot: quarter number, property class and submarket (something like this, could develop more, this one is more flexible)
set.seed(717)
pdp_quarters_submarket_class = partial(object = gbm_full,
                       train = model,
                       pred.var = c("quarter_num", "submarket", "PROP_CLA"),
                       n.trees = 2000,
                       pred.grid = data.frame(quarter_num = sort(rep(1:max(model$quarter_num), 100)), submarket = c(rep("inner", 20),rep("northeast", 20),rep("northwest", 20),rep("southeast", 20),rep("southwest", 20)), PROP_CLA = c("APARTMENT HO", "DETACHED HOU", "DUPLEX      ", "FLAT        ", "GROUP HOUSE ", "HOLIDAY UNIT", "HOME UNIT   ", "HOUSE       ", "HOUSE - FLAT", "HOUSE - GRAN", "HOUSE - LAND", "HOUSE - UNIT", "PATIO HOUSE ", "QUADRUPLEX  ", "ROW HOUSE   ", "SEMI-DETACHE", "TERRACE HOUS", "TOWN HOUSE  ", "TRIPLEX     ", "VILLA HOUSE ")))
```


#simply construct rppi, reference period is financial year 2011-2012
```{r}
baseline = mean(pdp_quarters[31:34,2])
pdp_quarters$index = exp(pdp_quarters$yhat - baseline) * 100
pdp_quarters_submarket$index = exp(pdp_quarters_submarket$yhat - baseline) * 100
pdp_quarters_class$index = exp(pdp_quarters_class$yhat - baseline) * 100
pdp_quarters_submarket_class$index = exp(pdp_quarters_submarket_class$yhat - baseline) * 100


ggplot(pdp_quarters, aes(quarter_num, index)) + geom_line()
ggplot(pdp_quarters_submarket, aes(quarter_num, index, color = submarket)) + geom_line()
ggplot(pdp_quarters_class, aes(quarter_num, index, color = PROP_CLA)) + geom_line()
```




#indexing rolling windows process
```{r}
#prepare windows for rolling process
for (i in 1:61) {
  temp_train = model[which(model$quarter_num <= (7+i) & model$quarter_num >= i),]
  
  assign(paste0("train_window_", i), temp_train)
}


#rolling window 8 quarters
for(i in 1:61){
  model_window = get(paste0("train_window_",i))
  
  #model in window
  set.seed(717)
  gbm_window = gbm(logprice ~ quarter_num + LAND_ARE + AREA_HSE + age + BEDS + BATHS + DINING + KITCHEN + FAMILY + STUDY + GAMES + LOUNGE + MEALS + carpark + LA_DESC + PROP_CLA + centlong + centlat + d_pool + d_brick + d_tile + TENCRT + submarket, data = model_window, distribution = "gaussian", n.trees = 2000, interaction.depth = 14, shrinkage = 0.05, n.minobsinnode = 15, bag.fraction = 0.5)
  
  #partial dependence plot: just 8 quarters
  set.seed(717)
  pdp_window = partial(object = gbm_window,
                       train = model_window,
                       pred.var = "quarter_num",
                       n.trees = 2000,
                       pred.grid = data.frame(quarter_num = 1:max(model_window$quarter_num)))
  
  #save model and pdp
  assign(paste0("gbm_window_",i), gbm_window)
  assign(paste0("pdp_window_",i), pdp_window)
  
  print(paste0("window ",i," is done."))
}
```
