---
title: "step_three_indexing"
author: "Zhuoran"
date: "17/11/2021"
output: html_document
---


#libraries
```{r}
library(foreign)
library(dplyr)
library(lubridate)
library(gbm)
library(pdp)
library(doParallel)
library(foreach)
library(ggplot2)
library(caret)
```


#hedonic indexing
#import data (if use train_test_split_backup, no need to run this)
```{r}
model_train_hedonic = read.csv("./data/raw_data_2004_2020_RPPI_hedonic_train.csv")[-1]

model_train_hedonic$LA_DESC = as.factor(model_train_hedonic$LA_DESC)
model_train_hedonic$PROP_CLA = as.factor(model_train_hedonic$PROP_CLA)
model_train_hedonic$submarket = as.factor(model_train_hedonic$submarket)
model_train_hedonic$logprice = log(model_train_hedonic$SALE1)
```


#prepare data for modeling
```{r}
model = data.frame(logprice = model_train_hedonic$logprice,
                   quarter_num = model_train_hedonic$quarter_num, 
                   LAND_ARE = model_train_hedonic$LAND_ARE, 
                   AREA_HSE = model_train_hedonic$AREA_HSE, 
                   age = model_train_hedonic$age, 
                   BEDS = model_train_hedonic$BEDS,
                   BATHS = model_train_hedonic$BATHS, 
                   DINING = model_train_hedonic$DINING, 
                   KITCHEN = model_train_hedonic$KITCHEN, 
                   FAMILY = model_train_hedonic$FAMILY, 
                   STUDY = model_train_hedonic$STUDY, 
                   GAMES = model_train_hedonic$GAMES, 
                   LOUNGE = model_train_hedonic$LOUNGE, 
                   MEALS = model_train_hedonic$MEALS, 
                   carpark = model_train_hedonic$carpark, 
                   LA_DESC = model_train_hedonic$LA_DESC, 
                   PROP_CLA = model_train_hedonic$PROP_CLA, 
                   centlong = model_train_hedonic$centlong, 
                   centlat = model_train_hedonic$centlat, 
                   TENCRT = model_train_hedonic$TENCRT,
                   d_pool = model_train_hedonic$d_pool, 
                   d_brick = model_train_hedonic$d_brick, 
                   d_tile = model_train_hedonic$d_tile)
```


#indexing full data process
```{r}
set.seed(717)
gbm_full = gbm(logprice ~ quarter_num + LAND_ARE + AREA_HSE + age + BEDS + BATHS + DINING + KITCHEN + FAMILY + STUDY + GAMES + LOUNGE + MEALS + carpark + LA_DESC + PROP_CLA + centlong + centlat + d_pool + d_brick + d_tile + TENCRT, data = model, distribution = "gaussian", n.trees = 2000, interaction.depth = 14, shrinkage = 0.05, n.minobsinnode = 15, bag.fraction = 0.5) #distribution = "laplace", if use laplace or MAE, two or more dimensional pdp generates the same predict numbers. Thus, gaussian (MSE) could be better. And then, paper one, the difference is negligible.


quarter_num = 1:68
LA_DESC = c("ARMADALE", "BASSENDEAN", "BAYSWATER", "BELMONT", "CAMBRIDGE", "CANNING", "CLAREMONT", "COCKBURN", "COTTESLOE", "EAST FREMANTLE", "FREMANTLE", "GOSNELLS", "JOONDALUP", "KALAMUNDA", "KWINANA", "MELVILLE", "MOSMAN PARK", "MUNDARING", "NEDLANDS", "PEPPERMINT GROVE", "PERTH CITY COUNCIL", "ROCKINGHAM", "SERPENTINE-JARRAHDALE", "SOUTH PERTH", "STIRLING", "SUBIACO", "SWAN", "VICTORIA PARK", "VINCENT", "WANNEROO")
PROP_CLA = c("APARTMENT HO", "DETACHED HOU", "DUPLEX", "FLAT", "GROUP HOUSE", "HOLIDAY UNIT", "HOME UNIT", "HOUSE", "HOUSE - FLAT", "HOUSE - GRAN", "HOUSE - LAND", "HOUSE - UNIT", "PATIO HOUSE", "QUADRUPLEX", "ROW HOUSE", "SEMI-DETACHE", "TERRACE HOUS", "TOWN HOUSE", "TRIPLEX", "VILLA HOUSE")

#partial dependence plot: just quarter number
set.seed(717)
pdp_quarters = partial(object = gbm_full,
                       train = model,
                       pred.var = "quarter_num",
                       n.trees = 2000,
                       pred.grid = data.frame(quarter_num = quarter_num))


#partial dependence plot: quarter number and lga
set.seed(717)
pdp_quarters_lga = partial(object = gbm_full,
                       train = model,
                       pred.var = c("quarter_num", "LA_DESC"),
                       n.trees = 2000,
                       pred.grid = data.frame(expand.grid(quarter_num = quarter_num, LA_DESC = LA_DESC)))


#partial dependence plot: quarter number and property class
set.seed(717)
pdp_quarters_class = partial(object = gbm_full,
                       train = model,
                       pred.var = c("quarter_num", "PROP_CLA"),
                       n.trees = 2000,
                       pred.grid = data.frame(expand.grid(quarter_num = quarter_num, PROP_CLA = PROP_CLA)))


#partial dependence plot: quarter number, property class and LGA (something like this, could develop more, this one is more flexible)
set.seed(717)
pdp_quarters_lga_class = partial(object = gbm_full,
                       train = model,
                       pred.var = c("quarter_num", "LA_DESC", "PROP_CLA"),
                       n.trees = 2000,
                       pred.grid = data.frame(expand.grid(quarter_num = quarter_num, LA_DESC = LA_DESC, PROP_CLA = PROP_CLA)))

save.image("./full_period_index.RData")
```


#simply construct rppi, reference period is financial year 2011-2012
```{r}
baseline = mean(pdp_quarters[31:34,2])
#pdp_quarters$index = exp(pdp_quarters$yhat - baseline) * 100
#pdp_quarters_lga$index = exp(pdp_quarters_lga$yhat - baseline) * 100
#pdp_quarters_class$index = exp(pdp_quarters_class$yhat - baseline) * 100
#pdp_quarters_lga_class$index = exp(pdp_quarters_lga_class$yhat - baseline) * 100

#ls
gbm_hedonic_index = data.frame(quarter = 1:68, index = exp(pdp_quarters$yhat - baseline) * 100)
write.csv(gbm_hedonic_index, "./data/gbm_hedonic_index.csv")
#lad
gbm_hedonic_index_lad = data.frame(quarter = 1:68, index = exp(pdp_quarters$yhat - baseline) * 100)
write.csv(gbm_hedonic_index_lad, "./data/gbm_hedonic_index_lad.csv")


ggplot(pdp_quarters, aes(quarter_num, index)) + geom_line()
ggplot(pdp_quarters_lga, aes(quarter_num, index, color = LA_DESC)) + geom_line()
ggplot(pdp_quarters_class, aes(quarter_num, index, color = PROP_CLA)) + geom_line()
```




#indexing rolling windows process
```{r}
#prepare windows for rolling process
for (i in 1:61) {
  temp_train = model[which(model$quarter_num <= (7+i) & model$quarter_num >= i),]
  
  assign(paste0("train_window_", i), temp_train)
}


#rolling window 8 quarters
for(i in 1:61){
  model_window = get(paste0("train_window_",i))
  
  #model in window
  set.seed(717)
  gbm_window = gbm(logprice ~ quarter_num + LAND_ARE + AREA_HSE + age + BEDS + BATHS + DINING + KITCHEN + FAMILY + STUDY + GAMES + LOUNGE + MEALS + carpark + LA_DESC + PROP_CLA + centlong + centlat + d_pool + d_brick + d_tile + TENCRT, data = model_window, distribution = "gaussian", n.trees = 2000, interaction.depth = 14, shrinkage = 0.05, n.minobsinnode = 15, bag.fraction = 0.5)
  
  #partial dependence plot: just 8 quarters
  set.seed(717)
  pdp_window = partial(object = gbm_window,
                       train = model_window,
                       pred.var = "quarter_num",
                       n.trees = 2000,
                       pred.grid = data.frame(quarter_num = min(model_window$quarter_num):max(model_window$quarter_num)))
  
  #save model and pdp
  assign(paste0("gbm_window_",i), gbm_window)
  assign(paste0("pdp_window_",i), pdp_window)
  
  print(paste0("window ",i," is done."))
}

save.image("./rolling_window_index.RData")
```






#resale indexing
#prepare resales
```{r}
#if use train_test_split_backpu, no need to run the next code
model_train_resale = read.csv("./data/raw_data_2004_2020_RPPI_repeatsales_train.csv")[-1]
resale = data.frame()
for (i in 1:(nrow(model_train_resale)-1)) {
  if(model_train_resale$PARCEL_I[i+1] == model_train_resale$PARCEL_I[i]){
    temp = data.frame(sale = model_train_resale$SALE1[i+1], date = model_train_resale$DATE1[i+1], sale_pre = model_train_resale$SALE1[i], date_pre = model_train_resale$DATE1[i], PROP_CLA = model_train_resale$PROP_CLA[i], LA_DESC = model_train_resale$LA_DESC[i])
    resale = rbind(resale, temp)
    print(i)
  }
}

resale$year = year(resale$date)
resale$year_pre = year(resale$date_pre)
resale$quarter = quarter(resale$date)
resale$quarter_pre = quarter(resale$date_pre)
resale$quarter_num = (resale$year - 2004) * 4 + resale$quarter
resale$quarter_num_pre = (resale$year_pre - 2004) * 4 + resale$quarter_pre

model = data.frame(log_diff = log(resale$sale) - log(resale$sale_pre), quarter = resale$quarter_num, quarter_pre = resale$quarter_num_pre, quarter_1 = 0, quarter_2 = 0)
model = fastDummies::dummy_cols(model, select_columns = c("quarter"))
for (i in 1:66) {
  model[which(model$quarter_pre == i),3+i] = -1
}
model = model[,-c(2,3,4)]
```


#resale index: case-shiller index
```{r}
lm_resale = lm(log_diff ~ . - 1, data = model)
#index
resale_index = data.frame(quarter = 1:68)
resale_index$index = exp(c(0, lm_resale$coefficients))
resale_index$index = (resale_index$index / mean(resale_index$index[31:34]))*100

write.csv(resale_index, "./data/resale_index.csv")
```




#test the quality of index
```{r}
resale_test = model_resale %>%
  filter(model_resale$resale_freq > 2)

resale_test$resale_indexed_sale = 0
resale_test$gbm_hedonic_indexed_sale = 0
resale_test$gbm_hedonic_indexed_sale_lad = 0

#forward predict
for (i in 1:(nrow(resale_test)-1)) {
  if(resale_test$PARCEL_I[i+1] == resale_test$PARCEL_I[i]){
    if(resale_test$train_test[i+1] == "test" & resale_test$train_test[i] == "train"){
      resale_test$resale_indexed_sale[i+1] = resale_test$SALE1[i] / resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i])] * resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i+1])]
      resale_test$gbm_hedonic_indexed_sale[i+1] = resale_test$SALE1[i] / gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i])] * gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i+1])]
      resale_test$gbm_hedonic_indexed_sale_lad[i+1] = resale_test$SALE1[i] / gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i])] * gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i+1])]
    }
  }
  print(i)
}
for (i in 1:(nrow(resale_test)-2)) {
  if(resale_test$PARCEL_I[i+2] == resale_test$PARCEL_I[i]){
    if(resale_test$train_test[i+2] == "test" & resale_test$train_test[i] == "train"){
      resale_test$resale_indexed_sale[i+2] = resale_test$SALE1[i] / resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i])] * resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i+2])]
      resale_test$gbm_hedonic_indexed_sale[i+2] = resale_test$SALE1[i] / gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i])] * gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i+2])]
      resale_test$gbm_hedonic_indexed_sale_lad[i+2] = resale_test$SALE1[i] / gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i])] * gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i+2])]
    }
  }
  print(i)
}
for (i in 1:(nrow(resale_test)-3)) {
  if(resale_test$PARCEL_I[i+3] == resale_test$PARCEL_I[i]){
    if(resale_test$train_test[i+3] == "test" & resale_test$train_test[i] == "train"){
      resale_test$resale_indexed_sale[i+3] = resale_test$SALE1[i] / resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i])] * resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i+3])]
      resale_test$gbm_hedonic_indexed_sale[i+3] = resale_test$SALE1[i] / gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i])] * gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i+3])]
      resale_test$gbm_hedonic_indexed_sale_lad[i+3] = resale_test$SALE1[i] / gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i])] * gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i+3])]
    }
  }
  print(i)
}
for (i in 1:(nrow(resale_test)-4)) {
  if(resale_test$PARCEL_I[i+4] == resale_test$PARCEL_I[i]){
    if(resale_test$train_test[i+4] == "test" & resale_test$train_test[i] == "train"){
      resale_test$resale_indexed_sale[i+4] = resale_test$SALE1[i] / resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i])] * resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i+4])]
      resale_test$gbm_hedonic_indexed_sale[i+4] = resale_test$SALE1[i] / gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i])] * gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i+4])]
      resale_test$gbm_hedonic_indexed_sale_lad[i+4] = resale_test$SALE1[i] / gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i])] * gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i+4])]
    }
  }
  print(i)
}
for (i in 1:(nrow(resale_test)-5)) {
  if(resale_test$PARCEL_I[i+5] == resale_test$PARCEL_I[i]){
    if(resale_test$train_test[i+5] == "test" & resale_test$train_test[i] == "train"){
      resale_test$resale_indexed_sale[i+5] = resale_test$SALE1[i] / resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i])] * resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i+5])]
      resale_test$gbm_hedonic_indexed_sale[i+5] = resale_test$SALE1[i] / gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i])] * gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i+5])]
      resale_test$gbm_hedonic_indexed_sale_lad[i+5] = resale_test$SALE1[i] / gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i])] * gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i+5])]
    }
  }
  print(i)
}
for (i in 1:(nrow(resale_test)-6)) {
  if(resale_test$PARCEL_I[i+6] == resale_test$PARCEL_I[i]){
    if(resale_test$train_test[i+6] == "test" & resale_test$train_test[i] == "train"){
      resale_test$resale_indexed_sale[i+6] = resale_test$SALE1[i] / resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i])] * resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i+6])]
      resale_test$gbm_hedonic_indexed_sale[i+6] = resale_test$SALE1[i] / gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i])] * gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i+6])]
      resale_test$gbm_hedonic_indexed_sale_lad[i+6] = resale_test$SALE1[i] / gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i])] * gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i+6])]
    }
  }
  print(i)
}


resale_test = resale_test %>%
  filter(resale_test$train_test == "test")

resale_test = resale_test %>%
  filter(resale_test$resale_indexed_sale > 0)

RMSE(log(resale_test$SALE1), log(resale_test$resale_indexed_sale))
median(log(resale_test$SALE1) - log(resale_test$resale_indexed_sale))
RMSE(log(resale_test$SALE1), log(resale_test$gbm_hedonic_indexed_sale))
median(log(resale_test$SALE1) - log(resale_test$gbm_hedonic_indexed_sale))
RMSE(log(resale_test$SALE1), log(resale_test$gbm_hedonic_indexed_sale_lad))
median(log(resale_test$SALE1) - log(resale_test$gbm_hedonic_indexed_sale_lad))

MAE(log(resale_test$SALE1), log(resale_test$resale_indexed_sale))
median(abs(log(resale_test$SALE1) - log(resale_test$resale_indexed_sale)))
MAE(log(resale_test$SALE1), log(resale_test$gbm_hedonic_indexed_sale))
median(abs(log(resale_test$SALE1) - log(resale_test$gbm_hedonic_indexed_sale)))
MAE(log(resale_test$SALE1), log(resale_test$gbm_hedonic_indexed_sale_lad))
median(abs(log(resale_test$SALE1) - log(resale_test$gbm_hedonic_indexed_sale_lad)))



#backward
resale_test = model_resale %>%
  filter(model_resale$resale_freq > 2)

resale_test$resale_indexed_sale = 0
resale_test$gbm_hedonic_indexed_sale = 0
resale_test$gbm_hedonic_indexed_sale_lad = 0

#backward predict
for (i in 1:(nrow(resale_test)-1)) {
  if(resale_test$PARCEL_I[i+1] == resale_test$PARCEL_I[i]){
    if(resale_test$train_test[i+1] == "train" & resale_test$train_test[i] == "test"){
      resale_test$resale_indexed_sale[i] = resale_test$SALE1[i+1] / resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i+1])] * resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i])]
      resale_test$gbm_hedonic_indexed_sale[i] = resale_test$SALE1[i+1] / gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i+1])] * gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i])]
      resale_test$gbm_hedonic_indexed_sale_lad[i] = resale_test$SALE1[i+1] / gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i+1])] * gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i])]
    }
  }
  print(i)
}
for (i in 1:(nrow(resale_test)-2)) {
  if(resale_test$PARCEL_I[i+2] == resale_test$PARCEL_I[i]){
    if(resale_test$train_test[i+2] == "train" & resale_test$train_test[i] == "test"){
      resale_test$resale_indexed_sale[i] = resale_test$SALE1[i+2] / resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i+2])] * resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i])]
      resale_test$gbm_hedonic_indexed_sale[i] = resale_test$SALE1[i+2] / gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i+2])] * gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i])]
      resale_test$gbm_hedonic_indexed_sale_lad[i] = resale_test$SALE1[i+2] / gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i+2])] * gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i])]
    }
  }
  print(i)
}
for (i in 1:(nrow(resale_test)-3)) {
  if(resale_test$PARCEL_I[i+3] == resale_test$PARCEL_I[i]){
    if(resale_test$train_test[i+3] == "train" & resale_test$train_test[i] == "test"){
      resale_test$resale_indexed_sale[i] = resale_test$SALE1[i+3] / resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i+3])] * resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i])]
      resale_test$gbm_hedonic_indexed_sale[i] = resale_test$SALE1[i+3] / gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i+3])] * gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i])]
      resale_test$gbm_hedonic_indexed_sale_lad[i] = resale_test$SALE1[i+3] / gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i+3])] * gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i])]
    }
  }
  print(i)
}
for (i in 1:(nrow(resale_test)-4)) {
  if(resale_test$PARCEL_I[i+4] == resale_test$PARCEL_I[i]){
    if(resale_test$train_test[i+4] == "train" & resale_test$train_test[i] == "test"){
      resale_test$resale_indexed_sale[i] = resale_test$SALE1[i+4] / resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i+4])] * resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i])]
      resale_test$gbm_hedonic_indexed_sale[i] = resale_test$SALE1[i+4] / gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i+4])] * gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i])]
      resale_test$gbm_hedonic_indexed_sale_lad[i] = resale_test$SALE1[i+4] / gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i+4])] * gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i])]
    }
  }
  print(i)
}
for (i in 1:(nrow(resale_test)-5)) {
  if(resale_test$PARCEL_I[i+5] == resale_test$PARCEL_I[i]){
    if(resale_test$train_test[i+5] == "train" & resale_test$train_test[i] == "test"){
      resale_test$resale_indexed_sale[i] = resale_test$SALE1[i+5] / resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i+5])] * resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i])]
      resale_test$gbm_hedonic_indexed_sale[i] = resale_test$SALE1[i+5] / gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i+5])] * gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i])]
      resale_test$gbm_hedonic_indexed_sale_lad[i] = resale_test$SALE1[i+5] / gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i+5])] * gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i])]
    }
  }
  print(i)
}
for (i in 1:(nrow(resale_test)-6)) {
  if(resale_test$PARCEL_I[i+6] == resale_test$PARCEL_I[i]){
    if(resale_test$train_test[i+6] == "train" & resale_test$train_test[i] == "test"){
      resale_test$resale_indexed_sale[i] = resale_test$SALE1[i+6] / resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i+6])] * resale_index$index[which(resale_index$quarter == resale_test$quarter_num[i])]
      resale_test$gbm_hedonic_indexed_sale[i] = resale_test$SALE1[i+6] / gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i+6])] * gbm_hedonic_index$index[which(gbm_hedonic_index$quarter == resale_test$quarter_num[i])]
      resale_test$gbm_hedonic_indexed_sale_lad[i] = resale_test$SALE1[i+6] / gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i+6])] * gbm_hedonic_index_lad$index[which(gbm_hedonic_index_lad$quarter == resale_test$quarter_num[i])]
    }
  }
  print(i)
}

resale_test = resale_test %>%
  filter(resale_test$train_test == "test")

resale_test = resale_test %>%
  filter(resale_test$resale_indexed_sale > 0)

RMSE(log(resale_test$SALE1), log(resale_test$resale_indexed_sale))
median(log(resale_test$SALE1) - log(resale_test$resale_indexed_sale))
RMSE(log(resale_test$SALE1), log(resale_test$gbm_hedonic_indexed_sale))
median(log(resale_test$SALE1) - log(resale_test$gbm_hedonic_indexed_sale))
RMSE(log(resale_test$SALE1), log(resale_test$gbm_hedonic_indexed_sale_lad))
median(log(resale_test$SALE1) - log(resale_test$gbm_hedonic_indexed_sale_lad))

MAE(log(resale_test$SALE1), log(resale_test$resale_indexed_sale))
median(abs(log(resale_test$SALE1) - log(resale_test$resale_indexed_sale)))
MAE(log(resale_test$SALE1), log(resale_test$gbm_hedonic_indexed_sale))
median(abs(log(resale_test$SALE1) - log(resale_test$gbm_hedonic_indexed_sale)))
MAE(log(resale_test$SALE1), log(resale_test$gbm_hedonic_indexed_sale_lad))
median(abs(log(resale_test$SALE1) - log(resale_test$gbm_hedonic_indexed_sale_lad)))
```


